[Variables]
App1Name=BioShock
App1=C:\Games\BioShock\Builds\Release\Bioshock.exe
Image1=Bioshockicon.png

App2Name=BioShock 2
App2=C:\Program Files (x86)\Bioshock\BioShock 2\SP\Builds\Binaries\Bioshock2Launcher.exe
Image2=BioShock2.ico

App3Name=BioShock Infinite
App3=C:\Games\BioShock Infinite\BioShock Infinite\Binaries\Win32\BioShockInfinite.exe
Image3=BioShockInfinite.ico

App4Name=Prototype 2
App4=C:\Games\Prototype 2\PROTOTYPE 2\prototype2.exe
Image4=Prototype2.ico

App5Name=World of Warcraft
App5=C:\Games\World of Warcraft 3.3.5a (no install)\Wow.exe
Image5=worldofwarcraft2

App6Name=League of Legends
App6=C:\Users\Niklas\Desktop\Desktop\Games\LeagueofLegends
Image6=4old

App7Name=Strife
App7=C:\Program Files (x86)\Strife\bin\strife.exe
Image7=Strife.ico

App8Name=Crysis 2
App8=C:\Games\Crysis 2\bin32\Crysis2.exe
Image8=Crysis2.png

CurrentApp=League of Legends
CurrentImage=4old
Current=C:\Users\Niklas\Desktop\Desktop\Games\LeagueofLegends
SSP="D:\Updates\MG\sql\Update 15-3-13\pgsql\,sic\Celeb"
CCCApp=App6
CCCName=App6Name
CCCImage=Image6
Show8=1
Show7=0
Show6=0
Show5=0
Show4=0
Show3=0
Show2=0
Show1=0
Decide2=0
Decide1=1