[Variables]
DarkLogin=60,46,61
CurrentFont=SAO UI Regular

;- TimeFlow -;
MinutesTint=120,255,255
; Neon
NeonHTint=181,0,255
NeonMTint=152,255,254,210

;- MinPCInfo -;
LineLaTint=241,0,255,180
LineLbTint=152,255,254,140

PCFontTint=204,204,254
PCSignTint=204,204,254

;- Visualizer -;
BarImage=Specials\SeeThrough6.png
BarImage2=Specials\SeeThrough1.png
BarImage3=Specials\SeeThrough1.png
BarImage4=Specials\SeeThrough6.png
; Flipped
FlipBarImage=Palettes\FlipFrost.png
FlipBarImage2=Specials\FlipPurple.png
FlipBarImage3=Specials\FlipPurple.png
FlipBarImage4=Palettes\FlipFrost.png

Bar1GS=0
Bar1GSON=1
Bar1Tint=255,0,254

Bar2GS=0
Bar2GSON=1
Bar2Tint=2,252,251

Bar3GS=0
Bar3GSON=1
Bar3Tint=2,252,251

Bar4GS=0
Bar4GSON=1
Bar4Tint=255,0,254

;- Weather -;
CityFontTint=255,0,254
TempFontTint=255,0,254
ConditionTint=118,227,255
WindFontTint=255,0,254
WindConditionFontTint=255,0,254
HideVisBG=0
HideVisBar=0

FontScale=10

Size10=((#WORKAREAWIDTH# * ((0.5 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((0.5 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size12=((#WORKAREAWIDTH# * ((0.6 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((0.6 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size14=((#WORKAREAWIDTH# * ((0.7 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((0.7 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size16=((#WORKAREAWIDTH# * ((0.8 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((0.8 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size18=((#WORKAREAWIDTH# * ((0.9 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((0.9 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size20=((#WORKAREAWIDTH# * ((1.0 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.0 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size22=((#WORKAREAWIDTH# * ((1.1 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.1 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size24=((#WORKAREAWIDTH# * ((1.2 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.2 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size25=((#WORKAREAWIDTH# * ((1.25 *(#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.25 *(#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size26=((#WORKAREAWIDTH# * ((1.3 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.3 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size28=((#WORKAREAWIDTH# * ((1.4 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.4 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size30=((#WORKAREAWIDTH# * ((1.5 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.5 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size32=((#WORKAREAWIDTH# * ((1.6 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.6 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size34=((#WORKAREAWIDTH# * ((1.7 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.7 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size36=((#WORKAREAWIDTH# * ((1.8 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.8 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size38=((#WORKAREAWIDTH# * ((1.9 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((1.9 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size40=((#WORKAREAWIDTH# * ((2.0 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((2.0 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size42=((#WORKAREAWIDTH# * ((2.1 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((2.1 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size44=((#WORKAREAWIDTH# * ((2.2 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((2.2 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size46=((#WORKAREAWIDTH# * ((2.3 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((2.3 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size48=((#WORKAREAWIDTH# * ((2.4 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((2.4 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
Size72=((#WORKAREAWIDTH# * ((3.6 * (#FontScale# * (#WORKAREAWIDTH# / 1440))) / 1440))+(#WORKAREAHEIGHT# * ((3.6 * (#FontScale# * (#WORKAREAHEIGHT# / 860))) / 860)))
