[Variables]
DarkLogin=60,46,61
CurrentFont=SAO UI Regular

;- TimeFlow -;
MinutesTint=120,255,255
; Neon
NeonHTint=191,0,205
NeonMTint=152,255,254,210

;- MinPCInfo -;
LineLaTint=241,0,255,180
LineLbTint=152,255,254,140

PCFontTint=249,209,194
PCSignTint=255,97,247

;- Visualizer -;
BarImage=Specials\SeeThrough6.png
BarImage2=Specials\SeeThrough1.png
BarImage3=Specials\SeeThrough1.png
BarImage4=Specials\SeeThrough6.png
; Flipped
FlipBarImage=Palettes\FlipFrost.png
FlipBarImage2=Specials\FlipPurple.png
FlipBarImage3=Specials\FlipPurple.png
FlipBarImage4=Palettes\FlipFrost.png

Bar1GS=0
Bar1GSON=1
Bar1Tint=255,0,254

Bar2GS=0
Bar2GSON=1
Bar2Tint=2,252,251

Bar3GS=0
Bar3GSON=1
Bar3Tint=2,252,251

Bar4GS=0
Bar4GSON=1
Bar4Tint=255,0,254

;- Weather -;
CityFontTint=255,0,254
TempFontTint=255,0,254
ConditionTint=118,227,255
WindFontTint=255,0,254
WindConditionFontTint=255,0,254
HideVisBG=0
HideVisBar=0

FontScale=10

Size10=((0.5 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(0.5 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size12=((0.6 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(0.6 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size14=((0.7 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(0.7 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size16=((0.8 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(0.8 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size18=((0.9 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(0.9 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size20=((1.0 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.0 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size22=((1.1 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.1 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size24=((1.2 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.2 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size25=((1.25 *(#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.25 *(#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size26=((1.3 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.3 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size28=((1.4 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.4 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size30=((1.5 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.5 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size32=((1.6 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.6 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size34=((1.7 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.7 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size36=((1.8 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.8 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size38=((1.9 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(1.9 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size40=((2.0 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(2.0 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size42=((2.1 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(2.1 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size44=((2.2 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(2.2 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size46=((2.3 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(2.3 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size48=((2.4 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(2.4 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))
Size72=((3.6 * (#FontScale# * (#WORKAREAWIDTH# / 1440)))+(3.6 * (#FontScale# * (#WORKAREAHEIGHT# / 860))))

; Chameleon
OldNeonHTint=191,0,205
OldNeonMTint=152,255,254,210
OldLineLaTint=241,0,255,180
OldLineLbTint=152,255,254,140
OldPCFontTint=249,209,194
OldPCSignTint=255,97,247
OldBar1Tint=255,0,254
OldBar2Tint=2,252,251
OldBar3Tint=2,252,251
OldBar4Tint=255,0,254
OldCityFontTint=237,205,115
OldTempFontTint=237,205,115
OldConditionTint=255,168,76
OldWindFontTint=237,205,115
OldWindConditionFontTint=237,205,115

VisualizerChameleonON=1
VisualizerChameleonOFF=0
TimeFlowChameleonON=1
TimeFlowChameleonOFF=0
PCInfoChameleonON=1
PCInfoChameleonOFF=0
WeatherChameleonON=1
WeatherChameleonOFF=0

VisualizerStatusX=#WORKAREAWIDTH# * 0.01736111111111111111111111111111
TimeFlowStatusX=#WORKAREAWIDTH# * 0.01736111111111111111111111111111
PCInfoStatusX=#WORKAREAWIDTH# * 0.01736111111111111111111111111111
WeatherStatusX=#WORKAREAWIDTH# * 0.01736111111111111111111111111111
