[Variables]
DarkLogin=60,46,61
CurrentFontFace=SAO UI Regular

;- TimeFlow -;
MinutesTint=120,255,255
; Neon
NeonHTint=96,0,198
NeonMTint=185,0,232,180

;- MinPCInfo -;
LineLaTint=64,0,165
LineLbTint=0,0,0

PCFontTint=204,204,254
PCSignTint=204,204,254

;- Visualizer -;
BarImage=Palettes\Frost.png
BarImage2=Specials\Purple.png
BarImage3=Palettes\Frost.png
BarImage4=Specials\Purple.png
; Flipped
FlipBarImage=Palettes\FlipFrost.png
FlipBarImage2=Specials\FlipPurple.png
FlipBarImage3=Palettes\FlipFrost.png
FlipBarImage4=Specials\FlipPurple.png

Bar1GS=0
Bar1GSON=0
Bar1Tint=255,0,254

Bar2GS=1
Bar2GSON=0
Bar2Tint=255,0,254

Bar3GS=0
Bar3GSON=0
Bar3Tint=255,0,254

Bar4GS=1
Bar4GSON=0
Bar4Tint=255,0,254

;- Weather -;
CityFontTint=185,0,232
TempFontTint=136,0,212
ConditionTint=109,0,198
WindFontTint=160,0,202
WindConditionFontTint=186,0,233
HideVisBG=0
HideVisBar=1
