function Initialize()

   StartingHours = SKIN:GetVariable('RemainingHours')
   StartingMinutes = SKIN:GetVariable('RemainingMinutes')
   StartingSeconds = SKIN:GetVariable('RemainingSeconds')
   
   TotalSeconds = (tonumber(StartingHours) * 3600) + (tonumber(StartingMinutes) * 60) + tonumber(StartingSeconds)
   SKIN:Bang('!SetOption', 'MeasureBarTime', 'MaxValue', TotalSeconds)
   
end --> Initialize

function Update()

   TotalSeconds = TotalSeconds - 1

   NowHours = math.floor(TotalSeconds / 3600)
   HoursRemainder = math.floor(TotalSeconds % 3600)
   NowMinutes = math.floor(HoursRemainder / 60)
   NowSeconds = math.floor(TotalSeconds % 60)

   SKIN:Bang('!SetVariable', 'RemainingHours', NowHours)
   SKIN:Bang('!SetVariable', 'RemainingMinutes', NowMinutes)
   SKIN:Bang('!SetVariable', 'RemainingSeconds', NowSeconds)
   SKIN:Bang('!SetOption', 'MeasureBarTime', 'Formula', ((NowHours*3600)+(NowMinutes*60)+NowSeconds))
   
   if TotalSeconds == 10 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-18r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-18r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-18r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-18r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-18r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','18r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-18r')
   end
   
   if TotalSeconds == 9 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-16r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-16r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-16r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-16r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-16r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','16r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-16r')
   end
   
   if TotalSeconds == 8 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-14r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-14r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-14r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-14r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-14r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','14r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-14r')
   end
      
   if TotalSeconds == 7 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-12r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-12r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-12r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-12r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-12r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','12r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-12r')
   end	  
	  
   if TotalSeconds == 6 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-10r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-10r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-10r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-10r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-10r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','10r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-10r')
   end
   
   if TotalSeconds == 5 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-8r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-8r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-8r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-8r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-8r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','8r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-8r')
   end

   if TotalSeconds == 4 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-6r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-6r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-6r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-6r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-6r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','6r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-6r')
   end
   
   if TotalSeconds == 3 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-4r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-4r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-4r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-4r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-4r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','4r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-4r')
   end
   
   if TotalSeconds == 2 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-2r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-2r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-2r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-2r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-2r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','2r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-2r')
   end
   
   if TotalSeconds == 1 then
      SKIN:Bang('!SetOption','MeterBand1y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand1y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand2y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand2y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand3y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand3y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand4y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand4y2','Y','-0r')  
      SKIN:Bang('!SetOption','MeterBand5y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand5y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand6y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand6y2','Y','-0r')  
      SKIN:Bang('!SetOption','MeterBand7y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand7y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand8y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand8y2','Y','-0r')
	  SKIN:Bang('!SetOption','MeterBand9y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand9y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand10y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand10y2','Y','-0r')
	  SKIN:Bang('!SetOption','MeterBand11y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand11y2','Y','-0r')
      SKIN:Bang('!SetOption','MeterBand12y','Y','0r')
	  SKIN:Bang('!SetOption','MeterBand12y2','Y','-0r')
   end
   
   if TotalSeconds == 0 then
	  SKIN:Bang('!DeactivateConfig','MinDos\\Gadgets\\Visualizer','Visualizer.ini')
   end
   
   
   return "H: "..tostring(NowHours).." M: "..tostring(NowMinutes).." S: "..tostring(NowSeconds)
      
end --> Update
